name: PR Check core-data-processing

on:
  pull_request:
    paths:
      - "core-data-processing/**"
    branches:
      - main

jobs:
  test-lint:
    name: Test & Lint (CPython & PyPy)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core-data-processing
    strategy:
      matrix:
        python-implementation: ["cpypy", "pypy"]
    steps:
      - uses: actions/checkout@v4
      - name: Read Python version
        id: python_version
        run: |
          PY_VERSION=$(cat core-data-processing/.python-version)
          echo "version=${PY_VERSION}" >> $GITHUB_OUTPUT
        working-directory: .
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.python_version.outputs.version }}
          python-implementation: ${{ matrix.python-implementation }}
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run black
        run: poetry run black --check core_data_processing
      - name: Run flake8
        run: poetry run flake8 core_data_processing
      - name: Run isort
        run: poetry run isort --check-only core_data_processing
      #   - name: Run mypy
      #     run: poetry run mypy core_data_processing
      - name: Run pytest
        run: poetry run pytest core_data_processing
