name: Publish core-data-processing to GitHub Packages

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Build & Publish to GitHub Packages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - name: Read Python version
        id: python_version
        run: |
          PY_VERSION=$(cat .python-version)
          echo "version=${PY_VERSION}" >> $GITHUB_OUTPUT
        working-directory: .
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.python_version.outputs.version }}
          cache: "pip"
      - name: Install Poetry
        run: pip install poetry
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
      - name: Set up Poetry cache
        uses: actions/cache@v3
        id: poetry-cache
        with:
          path: ./.venv
          key: poetry-${{ runner.os }}-${{ steps.python_version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-${{ steps.python_version.outputs.version }}-
      - name: Install dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install --only main
      - name: Build package
        run: poetry build
      - name: Publish to GitHub Packages
        env:
          POETRY_PYPI_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        run: poetry publish --build -r github
